version: '3.6'

services:

  expenses_bot:
    build: .
    volumes:
      - .:/app
    restart: on-failure
    environment:
      - DEBUG:${DEBUG}
      - DATABASE_URL=postgresql://${BOT_DB_USER}:${BOT_DB_PASSWORD}@${BOT_DB_HOST}:${BOT_DB_PORT}/${BOT_DB_NAME}
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "80:80"
    networks:
      - main

  redis:
    image: redis:alpine
    container_name: redis
    restart: on-failure
    expose:
      - 6379
    ports:
      - "6380:6379"
    networks:
      - main

networks:
  main: